#include "Localization.hpp"

namespace Localization {

static const Strings kStrings[] = {
    // 0: English
    {
        "File", "Edit", "View", "Performance", "Scenes", "Tools", "Help",
        "Settings", "Show Recordings", "Exit",
        "Undo", "Redo", "Transform",
        "Fullscreen", "Reset Layout", "Panels",
        "Preview", "Scenes", "Sources", "Audio Mixer", "Scene Transitions", "Controls",
        "Auto-Configuration Wizard", "About GDSR Studio",
        "Start Recording", "Stop Recording",
        "Settings", "Saving recording, please wait\u2026",
        "Duration",
        "Settings", "Appearance", "Theme", "Dark", "Light", "Language",
        "Font", "Font Size", "Close",
        "About GDSR Studio",
        "GDSR Studio \u2014 an OBS-style recording studio for Geometry Dash.",
        "Press F8 to show or hide the studio window.",
        "Press F8 to toggle",
        "GDSR Studio successfully loaded",
        "Press F8 to open",
        "FPS", "Resolution", "Quality (higher = smaller file)", "Encoder", "ffmpeg path", "Output folder",
        "Video", "Output",
        "Same as game",
        "Best quality", "Good", "Medium", "Fast encoding",
        "Not all GPUs support hardware encoders",
        "Mute", "Unmute",
        "Add scene", "Duplicate scene", "Reset scenes",
        "New Source",
        "Desktop Audio", "Microphone", "Enable", "Device", "Default device", "Audio bitrate", "Audio",
        "Potato", "Low", "Balanced", "Quality",
        "Refresh devices",
        "Performance",
        "Threaded capture (off render thread)",
        "Moves frame readback off GD's render thread. Disable if you see artifacts or instability.",
        "Borrow FPS from game (smooth recording)",
        "If recording can't keep up, the game slows down so every recorded frame is real. Turn off to keep game full speed (recording may stutter).",
        "Recording started",
        "Press F8 to reopen the studio",
    },
    // 1: Русский
    {
        "Файл", "Правка", "Вид", "Производительность", "Сцены", "Инструменты", "Помощь",
        "Настройки", "Показать записи", "Выход",
        "Отменить", "Повторить", "Трансформация",
        "Полный экран", "Сбросить расположение", "Панели",
        "Превью", "Сцены", "Источники", "Аудиомикшер", "Переходы сцен", "Управление",
        "Мастер настройки", "О программе GDSR Studio",
        "Начать запись", "Остановить запись",
        "Настройки", "Сохранение записи, подождите\u2026",
        "Длительность",
        "Настройки", "Оформление", "Тема", "Тёмная", "Светлая", "Язык",
        "Шрифт", "Размер шрифта", "Закрыть",
        "О программе GDSR Studio",
        "GDSR Studio \u2014 студия записи в стиле OBS для Geometry Dash.",
        "Нажмите F8, чтобы показать или скрыть окно студии.",
        "Нажмите F8 для переключения",
        "GDSR Studio успешно загружена",
        "Нажмите F8 чтобы открыть студию",
        "FPS", "Разрешение", "Качество (выше = меньше файл)", "Кодек", "Путь к ffmpeg", "Папка для записей",
        "Видео", "Вывод",
        "Как в игре",
        "Лучшее качество", "Хорошо", "Средне", "Быстрое кодирование",
        "Не все видеокарты поддерживают аппаратное кодирование",
        "Заглушить", "Включить",
        "Добавить сцену", "Дублировать сцену", "Сбросить сцены",
        "Новый источник",
        "Звук системы", "Микрофон", "Включить", "Устройство", "Устройство по умолчанию", "Битрейт аудио", "Аудио",
        "Картошка", "Низкая", "Сбалансированная", "Качество",
        "Обновить устройства",
        "Производительность",
        "Многопоточный захват (вне потока рендера)",
        "Выносит чтение кадров из потока рендера GD. Отключите при появлении артефактов или нестабильности.",
        "Заимствовать FPS у игры (плавная запись)",
        "Если кодирование не успевает, игра замедляется ради плавной записи. Отключите для полной скорости игры (запись может дёргаться).",
        "Запись началась",
        "Нажмите F8, чтобы снова открыть студию",
    },
    // 2: Español
    {
        "Archivo", "Editar", "Ver", "Rendimiento", "Escenas", "Herramientas", "Ayuda",
        "Ajustes", "Mostrar grabaciones", "Salir",
        "Deshacer", "Rehacer", "Transformar",
        "Pantalla completa", "Restablecer diseño", "Paneles",
        "Vista previa", "Escenas", "Fuentes", "Mezclador de audio", "Transiciones", "Controles",
        "Asistente de configuración", "Acerca de GDSR Studio",
        "Iniciar grabación", "Detener grabación",
        "Ajustes", "Guardando grabación, espere\u2026",
        "Duración",
        "Ajustes", "Apariencia", "Tema", "Oscuro", "Claro", "Idioma",
        "Fuente", "Tamaño de fuente", "Cerrar",
        "Acerca de GDSR Studio",
        "GDSR Studio \u2014 un estudio de grabación estilo OBS para Geometry Dash.",
        "Presiona F8 para mostrar u ocultar la ventana del estudio.",
        "Presiona F8 para alternar",
        "GDSR Studio cargado exitosamente",
        "Presiona F8 para abrir",
        "FPS", "Resolución", "Calidad (más alto = archivo más pequeño)", "Codificador", "Ruta de ffmpeg", "Carpeta de salida",
        "Video", "Salida",
        "Igual al juego",
        "Mejor calidad", "Buena", "Media", "Codificación rápida",
        "No todas las GPU admiten codificadores de hardware",
        "Silenciar", "Activar sonido",
        "Añadir escena", "Duplicar escena", "Restablecer escenas",
        "Nueva fuente",
        "Audio de escritorio", "Micrófono", "Activar", "Dispositivo", "Dispositivo predeterminado", "Bitrate de audio", "Audio",
        "Patata", "Bajo", "Equilibrado", "Calidad",
        "Actualizar dispositivos",
        "Rendimiento",
        "Captura en hilo separado",
        "Mueve la lectura de fotogramas fuera del hilo de renderizado. Desactívelo si ve artefactos o inestabilidad.",
        "Tomar FPS del juego (grabación fluida)",
        "Si la codificación no puede seguir el ritmo, el juego se ralentiza. Desactive para velocidad completa (la grabación puede tartamudear).",
        "Grabación iniciada",
        "Pulsa F8 para volver a abrir el estudio",
    },
    // 3: Português
    {
        "Arquivo", "Editar", "Ver", "Desempenho", "Cenas", "Ferramentas", "Ajuda",
        "Configurações", "Mostrar gravações", "Sair",
        "Desfazer", "Refazer", "Transformar",
        "Tela cheia", "Redefinir layout", "Painéis",
        "Pré-visualização", "Cenas", "Fontes", "Mixer de áudio", "Transições", "Controles",
        "Assistente de configuração", "Sobre o GDSR Studio",
        "Iniciar gravação", "Parar gravação",
        "Configurações", "Salvando gravação, aguarde\u2026",
        "Duração",
        "Configurações", "Aparência", "Tema", "Escuro", "Claro", "Idioma",
        "Fonte", "Tamanho da fonte", "Fechar",
        "Sobre o GDSR Studio",
        "GDSR Studio \u2014 um estúdio de gravação estilo OBS para Geometry Dash.",
        "Pressione F8 para mostrar ou ocultar a janela do estúdio.",
        "Pressione F8 para alternar",
        "GDSR Studio carregado com sucesso",
        "Pressione F8 para abrir",
        "FPS", "Resolução", "Qualidade (maior = arquivo menor)", "Codificador", "Caminho do ffmpeg", "Pasta de saída",
        "Vídeo", "Saída",
        "Igual ao jogo",
        "Melhor qualidade", "Boa", "Média", "Codificação rápida",
        "Nem todas as GPUs suportam codificadores de hardware",
        "Silenciar", "Ativar som",
        "Adicionar cena", "Duplicar cena", "Redefinir cenas",
        "Nova fonte",
        "Áudio do sistema", "Microfone", "Ativar", "Dispositivo", "Dispositivo padrão", "Bitrate de áudio", "Áudio",
        "Batata", "Baixo", "Equilibrado", "Qualidade",
        "Atualizar dispositivos",
        "Desempenho",
        "Captura em thread separada",
        "Move a leitura de quadros para fora da thread de renderização. Desative se houver artefatos ou instabilidade.",
        "Usar FPS do jogo (gravação suave)",
        "Se a codificação não acompanhar, o jogo desacelera. Desative para velocidade total (a gravação pode travar).",
        "Gravação iniciada",
        "Pressione F8 para reabrir o estúdio",
    },
    // 4: Deutsch
    {
        "Datei", "Bearbeiten", "Ansicht", "Leistung", "Szenen", "Werkzeuge", "Hilfe",
        "Einstellungen", "Aufnahmen anzeigen", "Beenden",
        "Rückgängig", "Wiederholen", "Transformieren",
        "Vollbild", "Layout zurücksetzen", "Panels",
        "Vorschau", "Szenen", "Quellen", "Audio-Mixer", "Szenübergänge", "Steuerung",
        "Konfigurationsassistent", "Über GDSR Studio",
        "Aufnahme starten", "Aufnahme stoppen",
        "Einstellungen", "Aufnahme wird gespeichert, bitte warten\u2026",
        "Dauer",
        "Einstellungen", "Darstellung", "Design", "Dunkel", "Hell", "Sprache",
        "Schriftart", "Schriftgröße", "Schließen",
        "Über GDSR Studio",
        "GDSR Studio \u2014 ein OBS-ähnliches Aufnahmestudio für Geometry Dash.",
        "Drücke F8, um das Studio-Fenster ein- oder auszublenden.",
        "F8 zum Umschalten",
        "GDSR Studio erfolgreich geladen",
        "F8 zum Öffnen drücken",
        "FPS", "Auflösung", "Qualität (höher = kleinere Datei)", "Encoder", "ffmpeg Pfad", "Ausgabeordner",
        "Video", "Ausgabe",
        "Wie im Spiel",
        "Beste Qualität", "Gut", "Mittel", "Schnelle Kodierung",
        "Nicht alle GPUs unterstützen Hardware-Encoder",
        "Stummschalten", "Stummschaltung aufheben",
        "Szene hinzufügen", "Szene duplizieren", "Szenen zurücksetzen",
        "Neue Quelle",
        "Desktop-Audio", "Mikrofon", "Aktivieren", "Gerät", "Standardgerät", "Audio-Bitrate", "Audio",
        "Kartoffel", "Niedrig", "Ausgewogen", "Qualität",
        "Geräte aktualisieren",
        "Leistung",
        "Threaded Capture (außerhalb Render-Thread)",
        "Verlagert das Auslesen der Frames aus dem Render-Thread. Bei Artefakten oder Instabilität deaktivieren.",
        "FPS vom Spiel borgen (flüssige Aufnahme)",
        "Wenn die Kodierung nicht nachkommt, wird das Spiel verlangsamt. Für volle Spielgeschwindigkeit deaktivieren (Aufnahme kann ruckeln).",
        "Aufnahme gestartet",
        "Drücke F8, um das Studio erneut zu öffnen",
    },
    // 5: 简体中文
    {
        "文件", "编辑", "视图", "性能", "场景", "工具", "帮助",
        "设置", "显示录制文件", "退出",
        "撤销", "重做", "变换",
        "全屏", "重置布局", "面板",
        "预览", "场景", "来源", "音频混音器", "场景过渡", "控制",
        "自动配置向导", "关于 GDSR Studio",
        "开始录制", "停止录制",
        "设置", "正在保存录制，请稍候\u2026",
        "持续时间",
        "设置", "外观", "主题", "暗色", "亮色", "语言",
        "字体", "字体大小", "关闭",
        "关于 GDSR Studio",
        "GDSR Studio \u2014 一款 OBS 风格的 Geometry Dash 录制工作室。",
        "按 F8 显示或隐藏工作室窗口。",
        "按 F8 切换",
        "GDSR Studio 加载成功",
        "按 F8 打开",
        "FPS", "分辨率", "质量（越高 = 文件越小）", "编码器", "ffmpeg 路径", "输出文件夹",
        "视频", "输出",
        "与游戏相同",
        "最佳质量", "良好", "中等", "快速编码",
        "并非所有显卡都支持硬件编码器",
        "静音", "取消静音",
        "添加场景", "复制场景", "重置场景",
        "新来源",
        "桌面音频", "麦克风", "启用", "设备", "默认设备", "音频比特率", "音频",
        "土豆", "低", "平衡", "质量",
        "刷新设备",
        "性能",
        "多线程捕获（脱离渲染线程）",
        "将帧读取移出GD的渲染线程。如出现画面异常或不稳定请禁用。",
        "借用游戏FPS（流畅录制）",
        "编码跟不上时游戏会减速以保证每帧真实。关闭可保持游戏全速（录制可能卡顿）。",
        "录制已开始",
        "按 F8 重新打开工作室",
    },
    // 6: Français
    {
        "Fichier", "\u00C9dition", "Affichage", "Performance", "Sc\u00E8nes", "Outils", "Aide",
        "Param\u00E8tres", "Afficher les enregistrements", "Quitter",
        "Annuler", "R\u00E9tablir", "Transformer",
        "Plein \u00E9cran", "R\u00E9initialiser la disposition", "Panneaux",
        "Aper\u00E7u", "Sc\u00E8nes", "Sources", "M\u00E9langeur audio", "Transitions", "Contr\u00F4les",
        "Assistant de configuration", "\u00C0 propos de GDSR Studio",
        "D\u00E9marrer l\u2019enregistrement", "Arr\u00EAter l\u2019enregistrement",
        "Param\u00E8tres", "Enregistrement en cours, veuillez patienter\u2026",
        "Dur\u00E9e",
        "Param\u00E8tres", "Apparence", "Th\u00E8me", "Sombre", "Clair", "Langue",
        "Police", "Taille de police", "Fermer",
        "\u00C0 propos de GDSR Studio",
        "GDSR Studio \u2014 un studio d\u2019enregistrement style OBS pour Geometry Dash.",
        "Appuyez sur F8 pour afficher ou masquer la fen\u00EAtre du studio.",
        "Appuyez sur F8 pour basculer",
        "GDSR Studio charg\u00E9 avec succ\u00E8s",
        "Appuyez sur F8 pour ouvrir",
        "FPS", "R\u00E9solution", "Qualit\u00E9 (plus \u00E9lev\u00E9 = fichier plus petit)", "Encodeur", "Chemin ffmpeg", "Dossier de sortie",
        "Vid\u00E9o", "Sortie",
        "Identique au jeu",
        "Meilleure qualit\u00E9", "Bonne", "Moyenne", "Encodage rapide",
        "Tous les GPU ne prennent pas en charge les encodeurs mat\u00E9riels",
        "Couper le son", "Activer le son",
        "Ajouter une sc\u00E8ne", "Dupliquer la sc\u00E8ne", "R\u00E9initialiser les sc\u00E8nes",
        "Nouvelle source",
        "Audio du bureau", "Microphone", "Activer", "P\u00E9riph\u00E9rique", "P\u00E9riph\u00E9rique par d\u00E9faut", "D\u00E9bit audio", "Audio",
        "Patate", "Bas", "\u00C9quilibr\u00E9", "Qualit\u00E9",
        "Actualiser les p\u00E9riph\u00E9riques",
        "Performance",
        "Capture multithread (hors thread de rendu)",
        "D\u00E9place la lecture des trames hors du thread de rendu. D\u00E9sactivez en cas d\u2019artefacts ou d\u2019instabilit\u00E9.",
        "Emprunter les FPS du jeu (enregistrement fluide)",
        "Si l\u2019encodage ne suit pas, le jeu ralentit. D\u00E9sactivez pour garder la pleine vitesse du jeu (l\u2019enregistrement peut saccader).",
        "Enregistrement démarré",
        "Appuyez sur F8 pour rouvrir le studio",
    },
    // 7: 日本語
    {
        "ファイル", "編集", "表示", "パフォーマンス", "シーン", "ツール", "ヘルプ",
        "設定", "録画を表示", "終了",
        "元に戻す", "やり直し", "変形",
        "フルスクリーン", "レイアウトをリセット", "パネル",
        "プレビュー", "シーン", "ソース", "オーディオミキサー", "シーン遷移", "コントロール",
        "自動設定ウィザード", "GDSR Studio について",
        "録画開始", "録画停止",
        "設定", "録画を保存中、お待ちください\u2026",
        "長さ",
        "設定", "外観", "テーマ", "ダーク", "ライト", "言語",
        "フォント", "フォントサイズ", "閉じる",
        "GDSR Studio について",
        "GDSR Studio \u2014 Geometry Dash用のOBSスタイル録画スタジオ。",
        "F8を押してスタジオウィンドウを表示/非表示にします。",
        "F8で切り替え",
        "GDSR Studioが正常に読み込まれました",
        "F8で開く",
        "FPS", "解像度", "品質（高い = ファイルサイズ小）", "エンコーダー", "ffmpegのパス", "出力フォルダ",
        "ビデオ", "出力",
        "ゲームと同じ",
        "最高品質", "良好", "中", "高速エンコード",
        "すべてのGPUがハードウェアエンコーダーをサポートしているわけではありません",
        "ミュート", "ミュート解除",
        "シーンを追加", "シーンを複製", "シーンをリセット",
        "新しいソース",
        "デスクトップ音声", "マイク", "有効", "デバイス", "デフォルトデバイス", "音声ビットレート", "音声",
        "ポテト", "低", "バランス", "品質",
        "デバイスを更新",
        "パフォーマンス",
        "スレッドキャプチャ（レンダースレッド外）",
        "GDのレンダースレッド外でフレーム読み取り。アーティファクトや不安定な場合は無効にしてください。",
        "ゲームのFPSを借用（スムーズな録画）",
        "エンコードが追いつかない場合ゲームが遅くなります。ゲームをフルスピードに保つには無効に（録画がカクつく可能性あり）。",
        "録画を開始しました",
        "F8でスタジオを再表示",
    },
    // 8: 한국어
    {
        "파일", "편집", "보기", "성능", "씬", "도구", "도움말",
        "설정", "녹화 파일 보기", "종료",
        "실행 취소", "다시 실행", "변환",
        "전체 화면", "레이아웃 초기화", "패널",
        "미리보기", "씬", "소스", "오디오 믹서", "씬 전환", "컨트롤",
        "자동 설정 마법사", "GDSR Studio 정보",
        "녹화 시작", "녹화 중지",
        "설정", "녹화 저장 중, 잠시만 기다려주세요\u2026",
        "지속 시간",
        "설정", "외관", "테마", "어두운", "밝은", "언어",
        "글꼴", "글꼴 크기", "닫기",
        "GDSR Studio 정보",
        "GDSR Studio \u2014 Geometry Dash용 OBS 스타일 녹화 스튜디오.",
        "F8을 눌러 스튜디오 창을 표시하거나 숨깁니다.",
        "F8로 전환",
        "GDSR Studio가 성공적으로 로드되었습니다",
        "F8을 눌러 열기",
        "FPS", "해상도", "품질 (높을수록 = 파일 크기 작음)", "인코더", "ffmpeg 경로", "출력 폴더",
        "비디오", "출력",
        "게임과 동일",
        "최고 품질", "좋음", "보통", "빠른 인코딩",
        "모든 GPU가 하드웨어 인코더를 지원하는 것은 아닙니다",
        "음소거", "음소거 해제",
        "씬 추가", "씬 복제", "씬 초기화",
        "새 소스",
        "데스크톱 오디오", "마이크", "활성화", "장치", "기본 장치", "오디오 비트레이트", "오디오",
        "감자", "낮음", "균형", "품질",
        "장치 새로고침",
        "성능",
        "스레드 캡처 (렌더 스레드 외부)",
        "GD 렌더 스레드 외부에서 프레임을 읽습니다. 화면 이상이나 불안정 시 비활성화하세요.",
        "게임 FPS 빌리기 (부드러운 녹화)",
        "인코딩이 따라가지 못하면 게임이 느려집니다. 게임 속도를 유지하려면 비활성화 (녹화가 끊길 수 있음).",
        "녹화가 시작되었습니다",
        "F8을 눌러 스튜디오 다시 열기",
    },
    // 9: Italiano
    {
        "File", "Modifica", "Visualizza", "Prestazioni", "Scene", "Strumenti", "Aiuto",
        "Impostazioni", "Mostra registrazioni", "Esci",
        "Annulla", "Ripeti", "Trasforma",
        "Schermo intero", "Ripristina layout", "Pannelli",
        "Anteprima", "Scene", "Sorgenti", "Mixer audio", "Transizioni", "Controlli",
        "Configurazione guidata", "Informazioni su GDSR Studio",
        "Avvia registrazione", "Ferma registrazione",
        "Impostazioni", "Salvataggio registrazione, attendere\u2026",
        "Durata",
        "Impostazioni", "Aspetto", "Tema", "Scuro", "Chiaro", "Lingua",
        "Carattere", "Dimensione carattere", "Chiudi",
        "Informazioni su GDSR Studio",
        "GDSR Studio \u2014 uno studio di registrazione stile OBS per Geometry Dash.",
        "Premi F8 per mostrare o nascondere la finestra dello studio.",
        "Premi F8 per attivare/disattivare",
        "GDSR Studio caricato con successo",
        "Premi F8 per aprire",
        "FPS", "Risoluzione", "Qualit\u00E0 (pi\u00F9 alto = file pi\u00F9 piccolo)", "Encoder", "Percorso ffmpeg", "Cartella di output",
        "Video", "Output",
        "Uguale al gioco",
        "Qualit\u00E0 migliore", "Buona", "Media", "Codifica veloce",
        "Non tutte le GPU supportano gli encoder hardware",
        "Silenzia", "Riattiva audio",
        "Aggiungi scena", "Duplica scena", "Ripristina scene",
        "Nuova sorgente",
        "Audio desktop", "Microfono", "Abilita", "Dispositivo", "Dispositivo predefinito", "Bitrate audio", "Audio",
        "Patata", "Basso", "Bilanciato", "Qualit\u00E0",
        "Aggiorna dispositivi",
        "Prestazioni",
        "Cattura in thread separato",
        "Sposta la lettura dei frame fuori dal thread di rendering. Disattiva in caso di artefatti o instabilit\u00E0.",
        "Prendi FPS dal gioco (registrazione fluida)",
        "Se la codifica non tiene il passo, il gioco rallenta. Disattiva per mantenere la piena velocit\u00E0 (la registrazione potrebbe scattare).",
        "Registrazione avviata",
        "Premi F8 per riaprire lo studio",
    },
    // 10: Polski
    {
        "Plik", "Edycja", "Widok", "Wydajność", "Sceny", "Narzędzia", "Pomoc",
        "Ustawienia", "Pokaż nagrania", "Zakończ",
        "Cofnij", "Ponów", "Przekształć",
        "Pełny ekran", "Resetuj układ", "Panele",
        "Podgląd", "Sceny", "Źródła", "Mikser audio", "Przejścia scen", "Kontrolki",
        "Kreator konfiguracji", "O GDSR Studio",
        "Rozpocznij nagrywanie", "Zatrzymaj nagrywanie",
        "Ustawienia", "Zapisywanie nagrania, proszę czekać\u2026",
        "Czas trwania",
        "Ustawienia", "Wygląd", "Motyw", "Ciemny", "Jasny", "Język",
        "Czcionka", "Rozmiar czcionki", "Zamknij",
        "O GDSR Studio",
        "GDSR Studio \u2014 studio nagrań w stylu OBS dla Geometry Dash.",
        "Naciśnij F8, aby pokazać lub ukryć okno studia.",
        "Naciśnij F8, aby przełączyć",
        "GDSR Studio pomyślnie załadowane",
        "Naciśnij F8, aby otworzyć",
        "FPS", "Rozdzielczość", "Jakość (wyższa = mniejszy plik)", "Koder", "Ścieżka ffmpeg", "Folder wyjściowy",
        "Wideo", "Wyjście",
        "Tak jak w grze",
        "Najlepsza jakość", "Dobra", "Średnia", "Szybkie kodowanie",
        "Nie wszystkie GPU obsługują kodery sprzętowe",
        "Wycisz", "Włącz dźwięk",
        "Dodaj scenę", "Duplikuj scenę", "Resetuj sceny",
        "Nowe źródło",
        "Dźwięk systemu", "Mikrofon", "Włącz", "Urządzenie", "Urządzenie domyślne", "Przepływność audio", "Audio",
        "Ziemniak", "Niski", "Zrównoważony", "Jakość",
        "Odśwież urządzenia",
        "Wydajność",
        "Przechwytywanie w osobnym wątku",
        "Przenosi odczyt klatek poza wątek renderowania GD. Wyłącz przy artefaktach lub niestabilności.",
        "Pożycz FPS z gry (płynne nagrywanie)",
        "Jeśli kodowanie nie nadąża, gra zwalnia. Wyłącz dla pełnej prędkości gry (nagranie może się zacinać).",
        "Nagrywanie rozpoczęte",
        "Naciśnij F8, aby ponownie otworzyć studio",
    },
    // 11: Türkçe
    {
        "Dosya", "Düzenle", "Görünüm", "Performans", "Sahneler", "Araçlar", "Yardım",
        "Ayarlar", "Kayıtları göster", "Çıkış",
        "Geri al", "Yinele", "Dönüştür",
        "Tam ekran", "Düzeni sıfırla", "Paneller",
        "Önizleme", "Sahneler", "Kaynaklar", "Ses Mikseri", "Sahne Geçişleri", "Kontroller",
        "Otomatik Yapılandırma Sihirbazı", "GDSR Studio Hakkında",
        "Kaydı başlat", "Kaydı durdur",
        "Ayarlar", "Kayıt kaydediliyor, lütfen bekleyin\u2026",
        "Süre",
        "Ayarlar", "Görünüm", "Tema", "Koyu", "Açık", "Dil",
        "Yazı tipi", "Yazı tipi boyutu", "Kapat",
        "GDSR Studio Hakkında",
        "GDSR Studio \u2014 Geometry Dash için OBS tarzı bir kayıt stüdyosu.",
        "Stüdyo penceresini göstermek veya gizlemek için F8'e basın.",
        "F8 ile değiştir",
        "GDSR Studio başarıyla yüklendi",
        "Açmak için F8'e basın",
        "FPS", "Çözünürlük", "Kalite (yüksek = daha küçük dosya)", "Kodlayıcı", "ffmpeg yolu", "Çıktı klasörü",
        "Video", "Çıktı",
        "Oyunla aynı",
        "En iyi kalite", "İyi", "Orta", "Hızlı kodlama",
        "Tüm GPU'lar donanım kodlayıcıları desteklemez",
        "Sesi kapat", "Sesi aç",
        "Sahne ekle", "Sahneyi çoğalt", "Sahneleri sıfırla",
        "Yeni Kaynak",
        "Masaüstü Sesi", "Mikrofon", "Etkinleştir", "Cihaz", "Varsayılan cihaz", "Ses bit hızı", "Ses",
        "Patates", "Düşük", "Dengeli", "Kalite",
        "Cihazları yenile",
        "Performans",
        "İş parçacıklı yakalama (render iş parçacığı dışında)",
        "Kare okumayı GD'nin render iş parçacığı dışına taşır. Hata veya kararsızlık durumunda devre dışı bırakın.",
        "Oyundan FPS ödünç al (akıcı kayıt)",
        "Kodlama yetişemezse oyun yavaşlar. Tam oyun hızı için devre dışı bırakın (kayıt takılabilir).",
        "Kayıt başladı",
        "Stüdyoyu yeniden açmak için F8'e basın",
    },
    // 12: Tiếng Việt
    {
        "Tệp", "Chỉnh sửa", "Xem", "Hiệu suất", "Cảnh", "Công cụ", "Trợ giúp",
        "Cài đặt", "Hiện bản ghi", "Thoát",
        "Hoàn tác", "Làm lại", "Biến đổi",
        "Toàn màn hình", "Đặt lại bố cục", "Bảng",
        "Xem trước", "Cảnh", "Nguồn", "Bộ trộn âm thanh", "Chuyển cảnh", "Điều khiển",
        "Thuật sĩ cấu hình", "Giới thiệu GDSR Studio",
        "Bắt đầu ghi", "Dừng ghi",
        "Cài đặt", "Đang lưu bản ghi, vui lòng chờ\u2026",
        "Thời lượng",
        "Cài đặt", "Giao diện", "Chủ đề", "Tối", "Sáng", "Ngôn ngữ",
        "Phông chữ", "Cỡ chữ", "Đóng",
        "Giới thiệu GDSR Studio",
        "GDSR Studio \u2014 studio ghi hình kiểu OBS cho Geometry Dash.",
        "Nhấn F8 để hiện hoặc ẩn cửa sổ studio.",
        "Nhấn F8 để chuyển đổi",
        "GDSR Studio đã tải thành công",
        "Nhấn F8 để mở",
        "FPS", "Độ phân giải", "Chất lượng (cao hơn = tệp nhỏ hơn)", "Bộ mã hóa", "Đường dẫn ffmpeg", "Thư mục đầu ra",
        "Video", "Đầu ra",
        "Giống trò chơi",
        "Chất lượng tốt nhất", "Tốt", "Trung bình", "Mã hóa nhanh",
        "Không phải tất cả GPU đều hỗ trợ bộ mã hóa phần cứng",
        "Tắt tiếng", "Bật tiếng",
        "Thêm cảnh", "Nhân đôi cảnh", "Đặt lại cảnh",
        "Nguồn mới",
        "Âm thanh máy tính", "Micrô", "Bật", "Thiết bị", "Thiết bị mặc định", "Tốc độ bit âm thanh", "Âm thanh",
        "Khoai tây", "Thấp", "Cân bằng", "Chất lượng",
        "Làm mới thiết bị",
        "Hiệu suất",
        "Chụp đa luồng (ngoài luồng kết xuất)",
        "Chuyển việc đọc khung hình ra khỏi luồng kết xuất. Tắt nếu thấy lỗi hoặc không ổn định.",
        "Mượn FPS từ game (ghi mượt)",
        "Nếu mã hóa không theo kịp, game sẽ chậm lại. Tắt để giữ tốc độ game đầy đủ (ghi có thể giật).",
        "Đã bắt đầu ghi",
        "Nhấn F8 để mở lại studio",
    },
    // 13: Bahasa Indonesia
    {
        "Berkas", "Edit", "Tampilan", "Kinerja", "Adegan", "Alat", "Bantuan",
        "Pengaturan", "Tampilkan rekaman", "Keluar",
        "Urungkan", "Ulangi", "Transformasi",
        "Layar penuh", "Atur ulang tata letak", "Panel",
        "Pratinjau", "Adegan", "Sumber", "Mixer Audio", "Transisi Adegan", "Kontrol",
        "Wizard Konfigurasi", "Tentang GDSR Studio",
        "Mulai merekam", "Hentikan perekaman",
        "Pengaturan", "Menyimpan rekaman, harap tunggu\u2026",
        "Durasi",
        "Pengaturan", "Tampilan", "Tema", "Gelap", "Terang", "Bahasa",
        "Font", "Ukuran Font", "Tutup",
        "Tentang GDSR Studio",
        "GDSR Studio \u2014 studio perekaman gaya OBS untuk Geometry Dash.",
        "Tekan F8 untuk menampilkan atau menyembunyikan jendela studio.",
        "Tekan F8 untuk beralih",
        "GDSR Studio berhasil dimuat",
        "Tekan F8 untuk membuka",
        "FPS", "Resolusi", "Kualitas (lebih tinggi = file lebih kecil)", "Encoder", "Path ffmpeg", "Folder output",
        "Video", "Output",
        "Sama seperti game",
        "Kualitas terbaik", "Bagus", "Sedang", "Encoding cepat",
        "Tidak semua GPU mendukung encoder perangkat keras",
        "Bisukan", "Aktifkan suara",
        "Tambah adegan", "Duplikasi adegan", "Atur ulang adegan",
        "Sumber Baru",
        "Audio Desktop", "Mikrofon", "Aktifkan", "Perangkat", "Perangkat default", "Bitrate audio", "Audio",
        "Kentang", "Rendah", "Seimbang", "Kualitas",
        "Segarkan perangkat",
        "Kinerja",
        "Tangkapan multithread (di luar thread render)",
        "Memindahkan pembacaan frame keluar dari thread render GD. Nonaktifkan jika melihat artefak atau ketidakstabilan.",
        "Pinjam FPS dari game (rekaman mulus)",
        "Jika encoding tidak bisa mengimbangi, game melambat. Nonaktifkan untuk kecepatan game penuh (rekaman mungkin tersendat).",
        "Perekaman dimulai",
        "Tekan F8 untuk membuka ulang studio",
    },
    // 14: Українська
    {
        "Файл", "Правка", "Вигляд", "Продуктивність", "Сцени", "Інструменти", "Допомога",
        "Налаштування", "Показати записи", "Вихід",
        "Скасувати", "Повторити", "Трансформація",
        "Повний екран", "Скинути розташування", "Панелі",
        "Прев'ю", "Сцени", "Джерела", "Аудіомікшер", "Переходи сцен", "Керування",
        "Майстер налаштування", "Про програму GDSR Studio",
        "Почати запис", "Зупинити запис",
        "Налаштування", "Збереження запису, зачекайте\u2026",
        "Тривалість",
        "Налаштування", "Оформлення", "Тема", "Темна", "Світла", "Мова",
        "Шрифт", "Розмір шрифту", "Закрити",
        "Про програму GDSR Studio",
        "GDSR Studio \u2014 студія запису в стилі OBS для Geometry Dash.",
        "Натисніть F8, щоб показати або приховати вікно студії.",
        "Натисніть F8 для перемикання",
        "GDSR Studio успішно завантажена",
        "Натисніть F8 щоб відкрити студію",
        "FPS", "Роздільна здатність", "Якість (вище = менший файл)", "Кодек", "Шлях до ffmpeg", "Папка для записів",
        "Відео", "Вивід",
        "Як у грі",
        "Найкраща якість", "Добре", "Середньо", "Швидке кодування",
        "Не всі відеокарти підтримують апаратне кодування",
        "Заглушити", "Увімкнути",
        "Додати сцену", "Дублювати сцену", "Скинути сцени",
        "Нове джерело",
        "Звук системи", "Мікрофон", "Увімкнути", "Пристрій", "Пристрій за замовчуванням", "Бітрейт аудіо", "Аудіо",
        "Картопля", "Низька", "Збалансована", "Якість",
        "Оновити пристрої",
        "Продуктивність",
        "Багатопотокове захоплення (поза потоком рендера)",
        "Виносить читання кадрів із потоку рендера GD. Вимкніть при появі артефактів або нестабільності.",
        "Позичити FPS у гри (плавний запис)",
        "Якщо кодування не встигає, гра сповільнюється. Вимкніть для повної швидкості гри (запис може смикатися).",
        "Запис розпочато",
        "Натисніть F8, щоб знову відкрити студію",
    },
};

static const char* kNativeNames[] = {
    "English",
    "\u0420\u0443\u0441\u0441\u043a\u0438\u0439",
    "Espa\u00f1ol",
    "Portugu\u00eas",
    "Deutsch",
    "\u7b80\u4f53\u4e2d\u6587",
    "Fran\u00e7ais",
    "\u65e5\u672c\u8a9e",
    "\ud55c\uad6d\uc5b4",
    "Italiano",
    "Polski",
    "T\u00fcrk\u00e7e",
    "Ti\u1ebfng Vi\u1ec7t",
    "Bahasa Indonesia",
    "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430",
};

static constexpr int kCount = 15;

static int g_lang = 0;

int count() { return kCount; }
const char* nativeName(int i) { return (i >= 0 && i < kCount) ? kNativeNames[i] : ""; }
void setLanguage(int index) { if (index >= 0 && index < kCount) g_lang = index; }
int language() { return g_lang; }
const Strings& L() { return kStrings[g_lang]; }

} // namespace Localization
